import type { ReportDefinition, ReportId } from "./types";

// Step 19A section 4: the governed catalog. Every entry is explicit, hand-authored metadata - never
// derived from a source module's own schema at runtime - so a definition's shape (filters, metrics,
// sections, limitations) is reviewable and stable independent of what any source module happens to
// return today. reportIds are preserved/matched against the illustrative names the UI-placeholder
// fixtures already imply (src/features/reports/fixtures/index.ts's "Monthly Partner",
// "Campaign / Event", "Cross-platform", "Long-period" catalog rows) wherever a stable slug made
// sense; the six section-12 "high-value" ids and the three additional fully-executed ids (Discovery
// Funnel, Partner Portfolio, Administration & Security) have no illustrative fixture precedent, so
// they use the product-authority's own plain family name.

const REPORT_CATALOG: Record<ReportId, ReportDefinition> = {
  // ---------------------------------------------------------------------------------------------
  // Section 12 "high-value" families - full execution.
  // ---------------------------------------------------------------------------------------------
  campaign_delivery: {
    reportId: "campaign_delivery",
    version: 1,
    title: "Campaign Delivery",
    purpose: "Fulfillment, timeliness and review/publication evidence for a Campaign's Assignments and Content, sourced from the Campaigns, Assignments and Content services.",
    sourceModules: ["campaigns", "assignments", "content"],
    requiredSourceFeatures: ["campaigns", "assignments", "content"],
    recordScopeNote: "Rows are exactly the Campaigns/Assignments/Content the acting user's own scope grants already permit listAssignments/listContent to return - no record outside that scope is ever included, counted, or referenced.",
    supportedFilters: [
      { id: "campaignRef", type: "campaignRef", label: "Campaign" },
      { id: "platform", type: "platform", label: "Platform" },
      { id: "status", type: "status", label: "Assignment status" },
    ],
    metrics: [
      { id: "assignmentCount", label: "Assignments in scope", meaning: "Count of actor-scoped Assignment rows returned by listAssignments for the applied filters." },
      { id: "completedAssignmentCount", label: "Completed assignments", meaning: "Assignments whose status is COMPLETED." },
      { id: "overdueAssignmentCount", label: "Overdue (brief due date passed, not completed)", meaning: "Assignments whose brief.dueAt is before generatedAt and status is not COMPLETED/CANCELLED.", unavailableMeaning: "Never fabricated - an Assignment with no brief.dueAt is excluded from this count entirely, not treated as on-time." },
      { id: "contentApprovedCount", label: "Content approved", meaning: "Content rows whose status is APPROVED." },
      { id: "contentUnderReviewCount", label: "Content under review", meaning: "Content rows whose status is UNDER_REVIEW or REVISION_REQUESTED." },
    ],
    sections: [{ id: "assignments", title: "Assignments" }, { id: "content", title: "Content" }],
    limitations: ["Bounded to the first page of each source module's own list function (see maxRows) - a Campaign with more Assignments/Content than that is reported truncated, never silently incomplete without disclosure."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  campaign_performance: {
    reportId: "campaign_performance",
    version: 1,
    title: "Campaign Performance",
    purpose: "Verified (MATCHED-evidence-only) Analytics outcomes for a Campaign's published Content, kept strictly per-platform.",
    sourceModules: ["analytics"],
    requiredSourceFeatures: ["analytics"],
    recordScopeNote: "Rows are exactly the actor-scoped Analytics content source records getPlatformAnalyticsView already returns for the applied platform - no cross-actor or cross-scope record is ever included.",
    supportedFilters: [
      { id: "campaignRef", type: "campaignRef", label: "Campaign" },
      { id: "platform", type: "platform", label: "Platform" },
    ],
    metrics: [
      { id: "matchedContentCount", label: "Matched content rows", meaning: "Content source records with matchState === MATCHED for the applied platform." },
      { id: "viewsByPlatform", label: "Views (per platform)", meaning: "Sum of the `views` metric across matched rows, kept separate per platform - never combined across platforms.", unavailableMeaning: "A platform with no matched rows reports null (unavailable), never 0." },
      { id: "engagementByPlatform", label: "Engagement (per platform)", meaning: "Sum of the `engagement` metric across matched rows, per platform.", unavailableMeaning: "Null when no matched row reports engagement for that platform - never 0." },
    ],
    sections: [{ id: "contentByPlatform", title: "Content by platform" }],
    limitations: [
      "Reach/impressions are not modeled by Analytics and are never substituted with views.",
      "Only MATCHED-evidence rows are counted; UNMATCHED/AMBIGUOUS source records are excluded from every metric (never guessed).",
      "Platform metrics are never combined into a single cross-platform total.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  channel_growth_freshness: {
    reportId: "channel_growth_freshness",
    version: 1,
    title: "Channel Growth & Freshness",
    purpose: "Partner Account follower snapshots with explicit source-timestamp freshness, distinguishing unavailable from stale evidence honestly.",
    sourceModules: ["analytics", "partners"],
    requiredSourceFeatures: ["analytics", "partners"],
    recordScopeNote: "Rows are exactly the actor-scoped channel/account rows getPartnerAnalyticsView already returns for the applied Partner - no record outside the actor's own Partner/Analytics scope is ever included.",
    supportedFilters: [
      { id: "partnerRef", type: "partnerRef", label: "Partner" },
      { id: "platform", type: "platform", label: "Platform" },
    ],
    metrics: [
      { id: "accountCount", label: "Accounts reported", meaning: "Count of Partner Account channel rows returned for the applied Partner/platform." },
      { id: "staleAccountCount", label: "Stale snapshots (>60 days old)", meaning: "Accounts whose latest snapshotAt is more than 60 days before generatedAt - Reports' own explicit staleness threshold (Analytics models no staleness concept of its own)." },
      { id: "unavailableAccountCount", label: "No snapshot on file", meaning: "Accounts with no channel source record at all - distinct from a stale one; never conflated." },
    ],
    sections: [{ id: "accounts", title: "Partner accounts" }],
    limitations: ["snapshotAt is the source record's own import time, not a live platform read - freshness is always relative to when CreatorOps last imported the data, never real-time.", "The 60-day staleness threshold is a Reports-defined disclosure convention, not a value Analytics itself asserts."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  partner_review_evidence: {
    reportId: "partner_review_evidence",
    version: 1,
    title: "Partner Review Evidence",
    purpose: "Finalized Partner Review evidence only, with Production, Compliance and Performance kept as fully separate sections - never blended into one score.",
    sourceModules: ["partner_reviews"],
    requiredSourceFeatures: ["partner_reviews"],
    recordScopeNote: "Rows are exactly the actor-scoped, FINALIZED Partner Review heads listPartnerReviewHeads already returns - no Draft/In Review/Superseded evidence is ever surfaced.",
    supportedFilters: [
      { id: "partnerRef", type: "partnerRef", label: "Partner" },
      { id: "period", type: "period", label: "Period (YYYY-MM)" },
    ],
    metrics: [
      { id: "finalizedReviewCount", label: "Finalized reviews", meaning: "Count of Partner Review heads with a non-null currentFinalizedVersion for the applied filters." },
      { id: "withComplianceEvidenceCount", label: "Reviews with Compliance evidence", meaning: "Finalized reviews whose Compliance section has at least one assignment entry." },
      { id: "withPerformanceEvidenceCount", label: "Reviews with Performance evidence", meaning: "Finalized reviews whose Performance section has at least one metric present." },
    ],
    sections: [{ id: "production", title: "Production" }, { id: "compliance", title: "Compliance" }, { id: "performance", title: "Performance" }],
    limitations: ["No blended/composite score is computed anywhere in this report - Production, Compliance and Performance are reported as three fully independent sections, matching Partner Reviews' own schema (which has no blended-score field either).", "Commercial evidence (deliverable/LFC-SFC/targets) is out of scope for this family in 19A."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  finance_status: {
    reportId: "finance_status",
    version: 1,
    title: "Finance Status",
    purpose: "Agreement/Payable/Invoice/Payment lifecycle and role-safe amount status per Partner/Vendor, through each Finance module's own safe workspace service.",
    sourceModules: ["finance-agreements", "finance-payables", "finance-invoices", "finance-payments"],
    requiredSourceFeatures: ["finance"],
    recordScopeNote: "Rows are exactly the actor-scoped workspace rows listAgreementsWorkspace/listPayablesWorkspace/listInvoicesWorkspace/listPaymentsWorkspace already return - amount fields already resolve to null (never a fabricated value) whenever the actor lacks the finance_amounts sensitive category, per each module's own amountsVisible gate.",
    supportedFilters: [
      { id: "partnerRef", type: "partnerRef", label: "Partner/Vendor counterparty" },
      { id: "status", type: "status", label: "Lifecycle status" },
    ],
    metrics: [
      { id: "activeAgreementCount", label: "Active agreements", meaning: "Agreement workspace rows with lifecycle === ACTIVE." },
      { id: "payableTotalAmountMinorSigned", label: "Payable net total (signed, minor units)", meaning: "Sum of PayableRowDto.totalAmountMinorSigned across in-scope Payables - the net signed payable amount, kept distinct from GST/TDS/gross figures.", unavailableMeaning: "Null (never 0) when amountsVisible is false for the acting role." },
      { id: "invoiceDeclaredGrossMinor", label: "Invoice declared gross total (minor units)", meaning: "Sum of InvoiceRowDto.declaredTotalMinor - the gross Invoice amount as declared by the supplier, kept distinct from Payable/Payment figures.", unavailableMeaning: "Null when amounts are not visible to the acting role." },
      { id: "paymentSettledMinor", label: "Payment settled total (minor units)", meaning: "Sum of PaymentRowDto.amountMinor across CONFIRMED payments - the actual recorded settlement amount, kept distinct from the expected net payment figure.", unavailableMeaning: "Null when amounts are not visible to the acting role." },
    ],
    sections: [{ id: "agreements", title: "Agreements" }, { id: "payables", title: "Payables" }, { id: "invoices", title: "Invoices" }, { id: "payments", title: "Payments" }],
    limitations: [
      "Amount fields are exactly those already exposed on each module's own bounded WORKSPACE ROW dto (avoiding a per-record detail fetch/N+1 fan-out) - the finer service-base/GST/TDS/expected-net-payment breakdown lives on each record's own detail view and is not repeated here; open the record itself for that breakdown.",
      "Service base / GST / gross Invoice / TDS / expected net payment / settlement amounts are always reported as separate figures - never summed together into one blended number.",
      "No PAN, Aadhaar, full bank account, restricted GSTIN, raw KYC or restricted extraction data ever appears in this report - each Finance module's own workspace DTO already omits them before Reports ever sees a row.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  operations_attention: {
    reportId: "operations_attention",
    version: 1,
    title: "Operations Attention",
    purpose: "Open Tasks, live pending Approval Queue items and scheduled/due Reminders needing attention - a live read composed fresh, never a second persisted approval/task truth.",
    sourceModules: ["operations"],
    requiredSourceFeatures: ["operations"],
    recordScopeNote: "Rows are exactly the actor-scoped Task/Reminder heads listTasks/listReminders already return, plus the Approval Queue items listApprovalQueue already returns (itself re-derived, per-item, from each source module's own gate) - no record outside the actor's own Operations/source scope is ever included.",
    supportedFilters: [{ id: "status", type: "status", label: "Task/Reminder status" }],
    metrics: [
      { id: "openTaskCount", label: "Open/in-progress/blocked tasks", meaning: "Task rows whose status is OPEN, IN_PROGRESS or BLOCKED." },
      { id: "overdueTaskCount", label: "Overdue tasks", meaning: "Task rows whose own isOverdue field (derived by Operations, never recomputed here) is true." },
      { id: "pendingApprovalCount", label: "Pending Approval Queue items", meaning: "Count of live Approval Queue items across all four source modules, exactly as listApprovalQueue reports today." },
      { id: "dueReminderCount", label: "Due reminders", meaning: "Reminder rows whose effective status (deriveReminderEffectiveStatus) is DUE." },
    ],
    sections: [{ id: "tasks", title: "Tasks" }, { id: "approvalQueue", title: "Approval Queue" }, { id: "reminders", title: "Reminders" }],
    limitations: ["The Approval Queue section is READ-ONLY and always live - Reports persists nothing about it (no second approval status), matching Operations' own Step 18A design.", "generatedAt/evidenceCutoff are identical for this report - there is no older 'evidence' than the read itself for live operational state."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 300,
  },
  // ---------------------------------------------------------------------------------------------
  // Additional fully-executed families with a real existing canonical source (beyond the
  // section-12 minimum six).
  // ---------------------------------------------------------------------------------------------
  discovery_funnel: {
    reportId: "discovery_funnel",
    version: 1,
    title: "Discovery Funnel",
    purpose: "Lead lifecycle-stage counts (research through conversion, and watchlist/rejected/archived) from the Discovery service.",
    sourceModules: ["discovery"],
    requiredSourceFeatures: ["discovery"],
    recordScopeNote: "Rows are exactly the actor-scoped Lead rows listLeads already returns for the applied filters - no Lead outside the actor's own scope is ever included, counted, or referenced.",
    supportedFilters: [{ id: "platform", type: "platform", label: "Platform" }],
    metrics: [
      { id: "leadCount", label: "Leads in scope", meaning: "Count of actor-scoped Lead rows returned by listLeads for the applied filters." },
      { id: "convertedCount", label: "Converted", meaning: "Lead rows with lifecycle === CONVERTED." },
      { id: "watchlistCount", label: "Watchlist", meaning: "Lead rows with lifecycle === WATCHLIST." },
      { id: "rejectedOrArchivedCount", label: "Rejected or archived", meaning: "Lead rows with lifecycle === REJECTED or ARCHIVED." },
    ],
    sections: [{ id: "byLifecycle", title: "Leads by lifecycle stage" }],
    limitations: ["Bounded to the first page listLeads returns (see maxRows) - a scope with more Leads than that is reported truncated."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  partner_portfolio: {
    reportId: "partner_portfolio",
    version: 1,
    title: "Partner Portfolio",
    purpose: "Partner status/tier/region portfolio counts from the Partners service.",
    sourceModules: ["partners"],
    requiredSourceFeatures: ["partners"],
    recordScopeNote: "Rows are exactly the actor-scoped Partner rows listPartners already returns for the applied filters - no Partner outside the actor's own scope is ever included.",
    supportedFilters: [{ id: "status", type: "status", label: "Partner status" }],
    metrics: [
      { id: "partnerCount", label: "Partners in scope", meaning: "Count of actor-scoped Partner rows returned by listPartners for the applied filters." },
      { id: "activeCount", label: "Active", meaning: "Partner rows with status === ACTIVE." },
      { id: "blacklistedCount", label: "Blacklisted", meaning: "Partner rows with status === BLACKLISTED." },
      { id: "pendingAccountSetupCount", label: "Pending Partner Account setup", meaning: "Partner rows with pendingPartnerAccountSetup === true." },
    ],
    sections: [{ id: "byStatus", title: "Partners by status" }],
    limitations: ["Bounded to the first page listPartners returns (see maxRows) - a scope with more Partners than that is reported truncated."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  administration_security: {
    reportId: "administration_security",
    version: 1,
    title: "Administration & Security",
    purpose: "Safe, label-only user/role/access-grant summary from the Administration service - no secret, token or raw auth internal ever leaves this report.",
    sourceModules: ["administration"],
    requiredSourceFeatures: ["administration"],
    recordScopeNote: "Rows are exactly the AdminUserDto rows listUsers already returns to this actor (Administration's own feature access already limits this to actors holding the administration feature grant - Super Admin only in the current seed).",
    supportedFilters: [{ id: "status", type: "status", label: "Active/inactive" }],
    metrics: [
      { id: "userCount", label: "Users in scope", meaning: "Count of AdminUserDto rows returned by listUsers for the applied filters." },
      { id: "activeUserCount", label: "Active users", meaning: "Users with active === true." },
      { id: "byRoleCount", label: "Users by role", meaning: "Count of users per role, from the same already-safe AdminUserDto.role field." },
    ],
    sections: [{ id: "byRole", title: "Users by role" }],
    limitations: ["No raw Firebase uid, session token, password, or override/audit before/after payload ever appears in this report - only the already-safe AdminUserDto fields (userRef, email, displayName, role, active).", "This report is only ever runnable by an actor who already holds real Administration FeatureAccess - Reports never widens who can see this data."],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  // ---------------------------------------------------------------------------------------------
  // Step 19A.1: the four "management-scale" families, given real governed execution. Per the
  // 19A.1 spec's own explicit per-family "Use:" lists (authoritative over 19A's stale placeholder
  // metadata): none of these four touch Finance - Monthly Partner Performance and Long-Period
  // Partner Programme's 19A-era sourceModules guess of finance-payables was never asked for by the
  // 19A.1 spec and is removed here to match what each family actually reads.
  // ---------------------------------------------------------------------------------------------
  monthly_partner_performance: {
    reportId: "monthly_partner_performance",
    version: 1,
    title: "Monthly Partner Performance",
    purpose: "A per-Partner, per-month view of Partner Account/platform coverage, per-platform Analytics output, and finalized Partner Review evidence - Production/Compliance/Performance kept fully separate. No blended score.",
    sourceModules: ["partners", "partner_reviews", "analytics", "content"],
    requiredSourceFeatures: ["partners", "partner_reviews", "analytics", "content"],
    recordScopeNote: "Rows are exactly the actor-scoped Partner/Partner-Account/Analytics/finalized-Review records listPartners (or getPartner)/getPlatformAnalyticsView/listPartnerReviewHeads+getPartnerReview already return for the applied filters - no record outside the actor's own scope is ever included.",
    supportedFilters: [
      { id: "partnerRef", type: "partnerRef", label: "Partner" },
      { id: "period", type: "period", label: "Period (YYYY-MM)" },
    ],
    metrics: [
      { id: "partnerCount", label: "Partners in scope", meaning: "Count of Partners in the bounded page (or the one requested Partner)." },
      { id: "finalizedReviewCount", label: "Partners with a finalized Review for the applied period", meaning: "Partners in scope whose Partner Review head has a non-null currentFinalizedVersion matching the applied partnerRef/period filters." },
      { id: "withComplianceEvidenceCount", label: "Reviews with Compliance evidence", meaning: "Finalized reviews (of the detailed subset) whose Compliance section has at least one assignment entry." },
      { id: "withPerformanceEvidenceCount", label: "Reviews with Performance evidence", meaning: "Finalized reviews (of the detailed subset) whose Performance section has at least one metric present." },
      { id: "accountCoverageCount_instagram", label: "Partners with a tracked Instagram account", meaning: "Partners in scope with at least one Instagram Partner Account row in this run.", unavailableMeaning: "Never fabricated - a Partner with no Instagram account row is simply not counted, not assumed to be zero-followers." },
      { id: "accountCoverageCount_youtube", label: "Partners with a tracked YouTube account", meaning: "Same as accountCoverageCount_instagram, for YouTube." },
      { id: "publishedContentCount_instagram", label: "Matched Instagram output", meaning: "Sum of MATCHED Instagram content rows across Partners in scope, kept separate from YouTube." },
      { id: "publishedContentCount_youtube", label: "Matched YouTube output", meaning: "Sum of MATCHED YouTube content rows across Partners in scope, kept separate from Instagram." },
      { id: "staleAccountCount_instagram", label: "Stale Instagram account snapshots (>60 days old)", meaning: "Reports-owned 60-day staleness convention (see channel_growth_freshness), applied per platform." },
      { id: "staleAccountCount_youtube", label: "Stale YouTube account snapshots (>60 days old)", meaning: "Same convention, for YouTube." },
    ],
    sections: [{ id: "production", title: "Production" }, { id: "compliance", title: "Compliance" }, { id: "performance", title: "Performance" }, { id: "topContent", title: "Top Content" }, { id: "dataQualityWarnings", title: "Data quality warnings" }],
    limitations: [
      "No blended score is computed anywhere in this report - Production, Compliance, Performance and per-platform Analytics metrics are reported as fully separate fields, never combined into one Partner performance number.",
      "Top Content is only computed when a single Partner is selected via the partnerRef filter (a bounded, single-partner Content query) - omitted for a multi-partner run to avoid an unbounded per-partner Content fan-out.",
      "Bounded to a page of at most 25 Partners when no partnerRef filter is applied, and full Review evidence detail to the first 20 finalized reviews found - a scope larger than that is reported truncated.",
      "Analytics rows are matched to a Partner by its resolved display-name label (Analytics carries no stored Partner ref on a content/account record) - a different Partner sharing the exact same display name cannot be distinguished.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  campaign_event_performance: {
    reportId: "campaign_event_performance",
    version: 1,
    title: "Campaign / Event Performance",
    purpose: "A combined Campaign delivery (Assignments/Content) + per-platform native Analytics outcome view for a Campaign - there is no separate Event entity in this product, so \"Event\" is treated as Campaign.",
    sourceModules: ["campaigns", "assignments", "content", "analytics"],
    requiredSourceFeatures: ["campaigns", "assignments", "content", "analytics"],
    recordScopeNote: "Rows are exactly the actor-scoped Assignment/Content records listAssignments/listContent already return, plus the actor-scoped Analytics content rows getPlatformAnalyticsView already returns for the applied Campaign - no record outside that scope is ever included.",
    supportedFilters: [
      { id: "campaignRef", type: "campaignRef", label: "Campaign" },
      { id: "platform", type: "platform", label: "Platform" },
    ],
    metrics: [
      { id: "assignmentCount", label: "Assignments in scope", meaning: "Count of actor-scoped Assignment rows returned by listAssignments for the applied filters." },
      { id: "completedAssignmentCount", label: "Completed assignments", meaning: "Assignments whose status is COMPLETED." },
      { id: "overdueAssignmentCount", label: "Overdue (brief due date passed, not completed)", meaning: "Assignments whose brief.dueAt is before generatedAt and status is not COMPLETED/CANCELLED.", unavailableMeaning: "An Assignment with no brief.dueAt is excluded from this count entirely, never treated as on-time." },
      { id: "contentApprovedCount", label: "Content approved", meaning: "Content rows whose status is APPROVED." },
      { id: "contentUnderReviewCount", label: "Content under review", meaning: "Content rows whose status is UNDER_REVIEW or REVISION_REQUESTED." },
      { id: "matchedContentCount_instagram", label: "Matched Instagram content", meaning: "MATCHED-evidence Instagram content rows for this Campaign.", unavailableMeaning: "0 when no matched row exists - a genuine count, not a missing-value case." },
      { id: "matchedContentCount_youtube", label: "Matched YouTube content", meaning: "MATCHED-evidence YouTube content rows for this Campaign." },
      { id: "views_instagram", label: "Instagram views", meaning: "Sum of the `views` metric across matched Instagram rows for this Campaign.", unavailableMeaning: "Null (never 0) when no matched row reports views." },
      { id: "views_youtube", label: "YouTube views", meaning: "Sum of the `views` metric across matched YouTube rows for this Campaign.", unavailableMeaning: "Null when no matched row reports views." },
      { id: "engagement_instagram", label: "Instagram engagement", meaning: "Sum of the `engagement` metric across matched Instagram rows for this Campaign.", unavailableMeaning: "Null when no matched row reports engagement." },
      { id: "engagement_youtube", label: "YouTube engagement", meaning: "Sum of the `engagement` metric across matched YouTube rows for this Campaign.", unavailableMeaning: "Null when no matched row reports engagement." },
    ],
    sections: [{ id: "assignedPartners", title: "Assigned Partners" }, { id: "assignments", title: "Assignments" }, { id: "content", title: "Content" }, { id: "contentByPlatform", title: "Content by platform" }, { id: "trajectoryByPlatform", title: "Trajectory by platform" }, { id: "contributorsByViews", title: "Contributors by Views" }, { id: "contributorsByEngagement", title: "Contributors by Engagement" }],
    limitations: [
      "There is no separate Event entity anywhere in this product - \"Event\" is treated as Campaign throughout this report, per its own definition; no Event entity is invented.",
      "Platform metrics are never combined into a single cross-platform total.",
      "Trajectory is the ordered set of individual matched-content data points within each platform's own bounded most-recent-content window, not a calendar-period aggregate trend.",
      "Contributors are ranked by exactly ONE explicit metric at a time (Views, separately Engagement) per platform - never a blended contributor score.",
      "Bounded to the first page of listAssignments/listContent (see maxRows) and each platform's own bounded Analytics read window - a Campaign larger than that is reported truncated.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 300,
  },
  cross_platform_partner_programme: {
    reportId: "cross_platform_partner_programme",
    version: 1,
    title: "Cross-Platform Partner / Programme",
    purpose: "A Partner/Programme view spanning Instagram and YouTube with every platform metric kept side by side as its own field - never blended, never a synthetic cross-platform score.",
    sourceModules: ["partners", "analytics"],
    requiredSourceFeatures: ["partners", "analytics"],
    recordScopeNote: "Rows are exactly the actor-scoped Partner rows listPartners (or getPartner) already returns, enriched with the actor-scoped Analytics rows getPlatformAnalyticsView already returns per platform - no record outside that scope is ever included.",
    supportedFilters: [{ id: "partnerRef", type: "partnerRef", label: "Partner" }],
    metrics: [
      { id: "partnerCount", label: "Partners in scope", meaning: "Count of Partners in the bounded page (or the one requested Partner)." },
      { id: "publishedContentCount_instagram", label: "Instagram published output", meaning: "Sum of MATCHED Instagram content rows across Partners in scope - kept separate from YouTube." },
      { id: "publishedContentCount_youtube", label: "YouTube published output", meaning: "Sum of MATCHED YouTube content rows across Partners in scope - kept separate from Instagram." },
      { id: "views_instagram", label: "Instagram views", meaning: "Sum of the `views` metric across matched Instagram rows.", unavailableMeaning: "Null (never 0) when no matched row reports views." },
      { id: "views_youtube", label: "YouTube views", meaning: "Sum of the `views` metric across matched YouTube rows.", unavailableMeaning: "Null when no matched row reports views." },
      { id: "engagement_instagram", label: "Instagram engagement", meaning: "Sum of the `engagement` metric across matched Instagram rows.", unavailableMeaning: "Null when no matched row reports engagement." },
      { id: "engagement_youtube", label: "YouTube engagement", meaning: "Sum of the `engagement` metric across matched YouTube rows.", unavailableMeaning: "Null when no matched row reports engagement." },
      { id: "followersKnownCount_instagram", label: "Partners with a known Instagram follower count", meaning: "Partners in scope whose latest Instagram account snapshot reports a non-null profileFollowers value." },
      { id: "followersKnownCount_youtube", label: "Partners with a known YouTube follower count", meaning: "Same, for YouTube." },
      { id: "publishedContentTotalAcrossPlatforms", label: "Total published content across tracked platforms", meaning: "The ONE metric this report combines across platforms: a raw sum of MATCHED Instagram + YouTube content rows. Safe to sum because each Content item is published on exactly one platform (no double-counting) and both platforms report the same unit (a count of items). Never applied to followers, views or engagement - see limitations." },
    ],
    sections: [{ id: "byPartner", title: "Partners by platform" }],
    limitations: [
      "Followers, Views and Engagement are always kept as fully separate per-platform figures (e.g. followers_instagram vs followers_youtube) - never summed or blended across platforms, and no synthetic cross-platform score is ever computed.",
      "The one exception, publishedContentTotalAcrossPlatforms, is explicitly defined on that metric above; it is never applied to followers/views/engagement, none of which share that same no-double-counting guarantee (the same person can follow a Partner on both platforms, and views/engagement are platform-native interaction counts with no shared cross-platform meaning).",
      "Bounded to a page of at most 25 Partners when no partnerRef filter is applied, and each platform's own bounded Analytics read window - a scope larger than that is reported truncated.",
      "Analytics rows are matched to a Partner by its resolved display-name label (Analytics carries no stored Partner ref on a content/account record) - a different Partner sharing the exact same display name cannot be distinguished.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 200,
  },
  long_period_partner_programme: {
    reportId: "long_period_partner_programme",
    version: 1,
    title: "Long-Period Partner Programme",
    purpose: "A bounded, explicit multi-period (up to 6 requested YYYY-MM periods) trend of one Partner's finalized Review evidence and per-platform Analytics output - never an open-ended date range, never fabricated roster/phase evolution.",
    sourceModules: ["partners", "partner_reviews", "analytics"],
    requiredSourceFeatures: ["partners", "partner_reviews", "analytics"],
    recordScopeNote: "Rows are exactly the actor-scoped, per-requested-period Partner Review evidence (listPartnerReviewHeads+getPartnerReview, one bounded call per period) and the actor-scoped Analytics rows getPlatformAnalyticsView already returns for the one requested Partner - no record outside that scope is ever included.",
    supportedFilters: [
      { id: "partnerRef", type: "partnerRef", label: "Partner (required)" },
      { id: "periods", type: "periodRange", label: "Periods (comma-separated YYYY-MM list, max 6, required)" },
    ],
    metrics: [
      { id: "requestedPeriodCount", label: "Periods requested", meaning: "Count of distinct valid YYYY-MM keys parsed from the periods filter, before the 6-period bound is applied." },
      { id: "coveredPeriodCount", label: "Periods covered by this run", meaning: "Count of periods actually evaluated - min(requestedPeriodCount, 6)." },
      { id: "droppedPeriodCount", label: "Periods dropped by the bound", meaning: "requestedPeriodCount - coveredPeriodCount - periods requested beyond the fixed 6-period bound, never silently included." },
      { id: "finalizedReviewCount", label: "Covered periods with a finalized Review", meaning: "Of the covered periods, how many have a finalized Partner Review for this Partner." },
      { id: "leaderPeriodByViews_instagram", label: "Highest-Views period (Instagram)", meaning: "The covered period with the highest summed Instagram views for this Partner - ranks by this ONE explicit metric only.", unavailableMeaning: "Null when no covered period has a positive Instagram views figure." },
      { id: "leaderPeriodByViews_youtube", label: "Highest-Views period (YouTube)", meaning: "Same, for YouTube.", unavailableMeaning: "Null when no covered period has a positive YouTube views figure." },
      { id: "leaderPeriodByEngagement_instagram", label: "Highest-Engagement period (Instagram)", meaning: "The covered period with the highest summed Instagram engagement for this Partner - ranks by this ONE explicit metric only.", unavailableMeaning: "Null when no covered period has a positive Instagram engagement figure." },
      { id: "leaderPeriodByEngagement_youtube", label: "Highest-Engagement period (YouTube)", meaning: "Same, for YouTube.", unavailableMeaning: "Null when no covered period has a positive YouTube engagement figure." },
    ],
    sections: [{ id: "production", title: "Production by period" }, { id: "compliance", title: "Compliance by period" }, { id: "performance", title: "Performance by period" }, { id: "periodCoverage", title: "Period coverage (requested vs. found)" }],
    limitations: [
      "Bounded to a maximum of 6 explicit period keys per request (never an open-ended date range) - both the partnerRef and periods filters are required; this report never runs for \"every Partner\" or \"every period\".",
      "Roster evolution is not shown: Partners has no historical/point-in-time roster snapshot per period - only current Partner state is queryable, so a genuine period-by-period roster reconstruction is not possible without fabrication.",
      "Account/platform EVOLUTION (a follower-count trend period-over-period) is not shown: Analytics' own platform view intentionally exposes only each account's single latest snapshot, never a history of snapshots - only whether that single latest snapshot falls inside a requested period is disclosed (a coverage check, not a trend).",
      "No programme-phase or milestone entity exists anywhere in this product - none is fabricated here.",
      "Output-by-period and per-period Views/Engagement are drawn only from each platform's own bounded most-recent-content window (the same bound every other Analytics-sourced Reports family uses) - a requested period whose matched content falls outside that recent window reports zero/unavailable, indistinguishable from a period with genuinely no evidence.",
      "No blended score and no cross-metric/cross-platform leader is ever computed - leaders rank by exactly one explicit metric at a time, per platform.",
    ],
    artifactFormats: ["pdf", "xlsx", "csv"],
    executionSupport: "full",
    maxRows: 50,
  },
};

export function getReportDefinition(reportId: ReportId): ReportDefinition {
  return REPORT_CATALOG[reportId];
}

export function listReportDefinitions(): ReportDefinition[] {
  return Object.values(REPORT_CATALOG);
}
